[package]
name = "micro_http"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2018"

[dependencies]
libc = ">=0.2.39"
mio = { version = "0.8.0", features = ["os-ext", "os-poll"]}

[dev-dependencies]
vmm-sys-util = ">=0.6.1"

[[bin]]
name = "testserver"
path = "bin/main.rs"